<a href="https://colab.research.google.com/github/Abhay182005dat/My_TensorFlow_Learning/blob/main/00_Tensorflow_)_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Introduction to Tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [2]:
  #Creating Tensors with tf.constant
scalar = tf.constant(7)
print(scalar)
scalar


tf.Tensor(7, shape=(), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[10,7],[7,10]])
matrix
matrix.ndim

2

In [7]:
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16)
another_matrix #specify data type by dytpr parameter


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [8]:
another_matrix.ndim

2

In [9]:
Tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
Tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [10]:
Tensor.ndim  # Basically the dimensions here mean just for remebering you can say that its the number of brackets they are enclose within ex. [[]] 2dim

3

What we've created so far :
* Scalar : a single number
* Vector : a number with direction (e.g. wind speed and direction)
* Matrix : a 2-dimensional array of numbers
* Tensor : an n-dimensional array of numbers

####Creating Tensors with `tf.variable`

In [11]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10.7])
changeable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([10.7], dtype=float32)>)

In [12]:
#You can change the changeable_tensor by only using the .assign method
# But you can't chnage the unchangeable_tensor even with the .assign method
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

###Creating Random Tensors

In [13]:
random_1  = tf.random.Generator.from_seed(42) # set seed for reproducibility or replicable etc 42 is the general convention
random_1 = random_1.normal(shape = (3,2))  # picks numbers from normal distribution
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))
# Are they Equal ?
random_1 , random_2 , random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###Shuffle the order of elements in tensor `tf.random.shuffle`

---



In [14]:
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
# not_shuffled.ndim = 2
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [15]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

**Practice** [`tf.random.set_seed`](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)

Imagine you have a magic dice that gives you a number every time you roll it. Usually, it gives a new, random number each time. But if you say a special word before you roll, like "abracadabra 42," it will always give you the same numbers in the same order every time you say "abracadabra 42" and roll it again.

In a computer, tf.random.set_seed is like saying that special word. When you set the seed (say "abracadabra 42"), the computer will remember and give you the same results whenever you "roll" (or run) your code again, making it feel a bit magical and predictable!

In [16]:
tf.random.set_seed(42)
notshuf =  tf.constant([[10,7],[3,4],[5,8]])
tf.random.shuffle(notshuf , seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  8]], dtype=int32)>

**practice end**

###Other ways to make Tensors

In [17]:
tf.ones([3,3] , tf.int32) #tf.ones(shape as input and datatype too)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [18]:
#tf.ones([10,3])  # default initialises float

#####Turn Numpy arrays into Tensors:

In [19]:
import numpy as np
a = np.arange(1,25,dtype = np.int32)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [20]:
A = tf.constant(a , shape = ([2,3,4])) #💡 You can give anything that should be equal to 24 why? because in the array a there are only 24 elements so 2*3*4 is 24
B = tf.constant(a)
A , B


(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

####Tensor attributes

1.   shape (number of elements in each of the dimensions) : tensor.shape
2.   Rank (Number of tensor dimensions)  : tensor.ndim
3.   axis or dimension (particular dimension of tensor)  :  tensor[0] , tensor[:,1]
4.   size (Total number of items in tensor) :  tf.size(tensor)


In [21]:
# Create a rank 4 tensor
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [22]:
print(rank_4_tensor.shape)
print(rank_4_tensor.ndim)
print("Element salong the 0 Axis :",rank_4_tensor.shape[0])
print("Elements along the last axis :",rank_4_tensor.shape[-1])
print(tf.size(rank_4_tensor))
print("Numpy",tf.size(rank_4_tensor).numpy()) # convert to numpy -> .numpy()

(2, 3, 4, 5)
4
Element salong the 0 Axis : 2
Elements along the last axis : 5
tf.Tensor(120, shape=(), dtype=int32)
Numpy 120


####Indexing Tensors (just like python)

In [23]:
# Get the first two elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [24]:
# Get the first element from each dimension from each index except for the final one
print(rank_4_tensor[:1 , :1, :1]) # also [:1,:1,:1,:] works
# If [:1,:1,:,:1] all elements except the 4th dimension one
print("\n")
print(rank_4_tensor[:1,:1,:1,:1])
print("\n")
print(rank_4_tensor[:1,:1,:,:1])

tf.Tensor([[[[0. 0. 0. 0. 0.]]]], shape=(1, 1, 1, 5), dtype=float32)


tf.Tensor([[[[0.]]]], shape=(1, 1, 1, 1), dtype=float32)


tf.Tensor(
[[[[0.]
   [0.]
   [0.]
   [0.]]]], shape=(1, 1, 4, 1), dtype=float32)


In [25]:
rank2tensor = tf.constant([[10,7],[3,4]])
rank2tensor.shape  , rank2tensor.ndim

(TensorShape([2, 2]), 2)

In [26]:
# Get the last item of each row  of our rank  2 tensor
rank2tensor[:,-1] # or rank2tensor[0: , 1:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

#### Expanding or adding a new dimension

In [27]:
# Add in extra dimension to the ran 2 tensor
rank3tensor = rank2tensor

In [28]:
rank3tensor = rank2tensor[: , : ,tf.newaxis]  # same as rank3tensor = rank2tensor[... , tf.newaxis]
rank3tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [29]:
# Alternative method
tf.expand_dims(rank2tensor,axis = -1) # -1 signifes the last dimension or final dimension

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [30]:
tf.expand_dims(rank2tensor,axis = 0) # dimension added at first

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating Tensors (Tensor operations)
**Basic Operations**

In [31]:
# You can add value to the Tensors
tensor = tf.constant([[10,7] , [3,4]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [32]:
# Original Tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [33]:
# Multiplication
tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [34]:
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [35]:
# We van use Tensorflow bulitin function too .math.multiply or .multiply etc
tf.multiply(tensor,10)  # When you use tensorflow functions the operations are sped up using gpu

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [36]:
tf.add( tensor ,1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  8],
       [ 4,  5]], dtype=int32)>

In [37]:
tf.pow(tensor , 2 )   # similarly many functions are available in tensorflow .maximum() , .minimum() , .is_finite() etc..

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

### Matrix Multiplication  `tf.linal.matmul`  ([Basic resource](https://www.mathsisfun.com/algebra/matrix-multiplying.html))
**Matrix multiplication is one of the most operations done in Ml**

Two short rules for Tensor Multiplication

*   The inner dimensions must match
*   The resulting dimension has the shape of the inner dimension





In [38]:
print(tensor)
tf.matmul(tensor ,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [39]:
# tensor * tensor is different its like tensor^2
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [40]:
# Hence you can multiply them with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [41]:
a = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
b = tf.constant([[3,5],[6,7],[1,8]])
tf.matmul(a , b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [42]:
c = tf.constant([[7,8,4],[3,9,10]])
# tf.matmul(a,c)  here Matrix multiplication is not possible has 3 and 2 doesn't match

In [43]:
# Hence we reshape c to 3,2 to match the shape
tf.reshape(c , shape = (3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 4,  3],
       [ 9, 10]], dtype=int32)>

In [44]:
# You can also transpose the matrix
tf.transpose(c)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  3],
       [ 8,  9],
       [ 4, 10]], dtype=int32)>

In [45]:
# Try Matrix Multiplication with Transpose rather than reshape()
tf.matmul(a , tf.transpose(c))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[43, 71],
       [69, 49],
       [57, 66]], dtype=int32)>

### Dot Product `tf.tensordot()`


In [46]:
X = tf.constant([[1,2],[3,4],[5,6]])
Y = tf.constant([[7,8],[9,10],[11,12]])
X , Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [47]:
#Performing the dot product
tf.tensordot(tf.transpose(X) , Y , axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [48]:
tf.tensordot(X , tf.transpose(Y) , axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [49]:
# Matrix Multiplication using transpose
tf.matmul(X , tf.transpose(Y))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [50]:
# Matrix Multiplication using reshape
tf.matmul(X, tf.reshape(Y , shape = (2,3)))            # You can see even you have used both the methods the answer are not the same why ? lets check out in next cell

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [51]:
# Check Values of Y
print('Normal Y :\n')
print(Y,"\n")
print("Reshaped Y :\n")
print(tf.reshape(Y , shape = (2,3)))
print('\n')
print("Transposed Y :\n")
print(tf.transpose(Y))

Normal Y :

tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Reshaped Y :

tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


Transposed Y :

tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Now i guess i know why it is different , reshape is just like reshuffling(one of the axes doesn't line up properly)  and transpose is the actual transpose of the matrix . Also the right way to multiply would be by transposing the matrix ❄

### Changing the datatype of Tensor

In [52]:
B = tf.constant([10. , 7.8])
B.dtype

tf.float32

In [53]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [54]:
# Change from float32 to float16  , This is called reduced precision
D = tf.cast(B , dtype = tf.float16 )  # Now they take less space on memory and run faster
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([10. ,  7.8], dtype=float16)>

In [55]:
E = tf.cast(C , dtype = tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [56]:
E_float16 = tf.cast(E , dtype = tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregating Tensors

**Aggregating tensors = condensing them from multiple values down to a smaller amount of values.**

In [57]:
# Get the absolute values
D = tf.constant([-7,10])
tf.abs(D)  # D is unchanged remember !

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

#### Lets do the following forms of aggregation

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor



In [58]:
A = tf.constant([1,2,3,4,5])
B = tf.constant([6,7,8,9,10])

In [59]:
tf.maximum(A,B )  # Both A and B should have the same datatypes

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 6,  7,  8,  9, 10], dtype=int32)>

In [60]:
tf.minimum(A,B)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [61]:
A = tf.constant([[1,2,3,4,5],[23,45,32,54,32]])
tf.maximum(A,B )

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 6,  7,  8,  9, 10],
       [23, 45, 32, 54, 32]], dtype=int32)>

In [62]:
tf.minimum(A,B)  # THESE MAXIMUM AND MINIMUM ARE DIFFERENT FUCTIONS AS COMPARED TO NORMAL MIN AND MAX

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int32)>

In [63]:
tf.reduce_mean(B) # Mean

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [64]:
tf.reduce_mean(A) #sum of all elements of A by 10

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [65]:
tf.reduce_min(B) #Original min and max

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [66]:
tf.reduce_max(A)

<tf.Tensor: shape=(), dtype=int32, numpy=54>

In [67]:
tf.reduce_sum(B)

<tf.Tensor: shape=(), dtype=int32, numpy=40>

####  Exercise : Find variance and standard deviation of the given `E` Tensor

In [68]:
E = tf.constant(np.random.randint(0,100 , size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([49, 51, 87, 37, 84,  7, 40, 14, 49,  1, 97, 16, 39, 20, 44,  9, 27,
       99, 48,  8, 73, 71,  0, 81, 33, 55,  0,  2, 31, 67, 11, 50, 38, 29,
       63, 87, 88, 15, 87, 61, 99, 64, 94, 39, 98, 24, 34, 78, 45, 81])>

In [69]:
variance = tf.math.reduce_variance(tf.cast(E , dtype = tf.float16 ))
variance

<tf.Tensor: shape=(), dtype=float16, numpy=934.0>

In [70]:
std = tf.math.reduce_std(tf.cast(E , dtype = tf.float16 ))
std

<tf.Tensor: shape=(), dtype=float16, numpy=30.56>

**Alternate method**

In [71]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=934>

In [72]:
tfp.stats.stddev(tf.cast(E , dtype = tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=30.56>

###Find the positional maximum and minimum
**These are like ,when a model gives out a probabilities of a particular item then the maximum one will be the correct item right so the same thing we areee going to do here**

In [73]:
# Create a new Tensor for finding positional maximum and minuimum
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [74]:
# Find the positional maximum
tf.argmax(F)  # the argmax returns the index of the higest probability

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [75]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [76]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [77]:
# Check for Equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [78]:
# Fid the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [79]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (Removing all single dimensions)

In [80]:
G = tf.constant(tf.random.uniform(shape = [50]) , shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [81]:
G_squeezed = tf.squeeze(G) # 't' is a tensor of shape [1, 2, 1, 3, 1, 1]
G_squeezed , G_squeezed.shape                         # tf.shape(tf.squeeze(t))  # [2, 3]

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding in Tensors

In [82]:
# Create a list of indices
some_list = [0,1,2,3] # say if red,yellow,blue,green are there then hot encoding just means the stage prior to applying to a neural network which is numerical processing,
                      # this a part of it. If it is the red's turn thena ll others turn to be '0' and red is '1'.
# One hot encode them
tf.one_hot(some_list , depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [83]:
tf.one_hot(some_list , depth = 3)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

In [84]:
# Specify custom values for one hot encoding
tf.one_hot(some_list , depth = 4 , on_value='I Love Deep Learning' , off_value='I Love Machine Learning')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I Love Deep Learning', b'I Love Machine Learning',
        b'I Love Machine Learning', b'I Love Machine Learning'],
       [b'I Love Machine Learning', b'I Love Deep Learning',
        b'I Love Machine Learning', b'I Love Machine Learning'],
       [b'I Love Machine Learning', b'I Love Machine Learning',
        b'I Love Deep Learning', b'I Love Machine Learning'],
       [b'I Love Machine Learning', b'I Love Machine Learning',
        b'I Love Machine Learning', b'I Love Deep Learning']],
      dtype=object)>

In [85]:
tf.one_hot(some_list , depth = 4 , on_value='ONE' , off_value='ZERO')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'ONE', b'ZERO', b'ZERO', b'ZERO'],
       [b'ZERO', b'ONE', b'ZERO', b'ZERO'],
       [b'ZERO', b'ZERO', b'ONE', b'ZERO'],
       [b'ZERO', b'ZERO', b'ZERO', b'ONE']], dtype=object)>

### Maths practice : Squaring  , log ,square root etc

In [86]:
# Create a new tensor
H = tf.range(1,10) # NOTE : 10 is exclusive
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [87]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [88]:
tf.sqrt(tf.cast(H , dtype = tf.float16)) # NOTE : sqrt accepts only float, bfloat16, half, float32, float64 etc..

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [89]:
# Find  the log
tf.math.log(tf.cast(H , dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [90]:
tf.math.is_strictly_increasing(H) # Checks if the tensor is in increasing order

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [91]:
E = tf.constant([1,2,3,4,5,8,12,13,12])
tf.math.greater_equal(H , E)  # Check if x >= y same way, less_equal works

<tf.Tensor: shape=(9,), dtype=bool, numpy=array([ True,  True,  True,  True,  True, False, False, False, False])>

In [92]:
tf.math.less_equal(H,E) # [1,2,3,4,5,6,7,8,9] < = [1,2,3,4,5,8,12,13,12]

<tf.Tensor: shape=(9,), dtype=bool, numpy=array([ True,  True,  True,  True,  True,  True,  True,  True,  True])>

### Tensors and  Numpy
Tensorflow interacts beautifully with NumPy arrays

In [93]:
# Create a Tensor directly from a Numpy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [94]:
# Convert tensor J to a Numpy Array
np.array(J) , type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [95]:
# Alternate way
J.numpy() , type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [96]:
# Acessing elements
J = tf.constant([3.])
J.numpy()

array([3.], dtype=float32)

In [97]:
J.numpy()[0]

3.0

In [98]:
# The deafult types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
# Check the datatypes of each
numpy_J.dtype , tensor_J.dtype

(tf.float64, tf.float32)

#### tetetetttaffasdgsgdgdfhdfgPractice Exercise

In [99]:
# Create the first tensor
tensor1 = tf.constant(np.random.rand(5, 300))
# Create the second tensor
tensor2 = tf.constant(np.random.rand(5,300,))
# To see the output, run the code.
#tensor1 , tensor2

In [100]:
tf.matmul(tensor1 , tf.transpose(tensor2))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[82.5920067 , 76.71514278, 78.09294049, 78.23286814, 74.36005327],
       [82.31144336, 73.50172979, 75.40800853, 73.87985831, 75.37579299],
       [79.49683234, 71.06201917, 72.30701859, 69.70301165, 70.59310701],
       [83.40050825, 78.11268986, 79.80851567, 78.21084457, 75.90394522],
       [79.35611208, 70.97587764, 75.75416193, 73.57616031, 70.21512973]])>

In [101]:
tf.tensordot( tensor1 , tf.transpose(tensor2) , axes = 1)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[82.5920067 , 76.71514278, 78.09294049, 78.23286814, 74.36005327],
       [82.31144336, 73.50172979, 75.40800853, 73.87985831, 75.37579299],
       [79.49683234, 71.06201917, 72.30701859, 69.70301165, 70.59310701],
       [83.40050825, 78.11268986, 79.80851567, 78.21084457, 75.90394522],
       [79.35611208, 70.97587764, 75.75416193, 73.57616031, 70.21512973]])>

In [102]:
tensor3 = tf.constant(np.random.rand(1,224,224,3))

In [103]:
#tf.squeeze(tensor3)

In [104]:
tensor4 = tf.constant([1,2,3,4,5,6,7,8,9,9])
tensor4

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9, 9], dtype=int32)>

In [105]:
tf.reduce_max(tensor4)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [106]:
tf.one_hot(tf.cast(tensor4 ,dtype = tf.int32) , depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

  End  of Practice

### Intro To Neural Network Regression using Tensorflow  Screenshot 2024-11-20 221345.png

Continued in NEXT NOTEBOOK ....