<a href="https://colab.research.google.com/github/Abhay182005dat/My_TensorFlow_Learning/blob/main/Integer_Encoding_simple_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
!pip install keras

In [46]:
import numpy as np
docs = [
    'go india',
    'india india',
    'hip hip hurray',
    'jeetega bhai jeetega india jeetega',
    'bharat mata ki jai',
    'kohli kohli',
    'sachin sachin',
    'dhoni dhoni',
    'modi ji ki jai',
    'hello world'

]


In [47]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token='<nothing>') # if in future we encounter any word which is not in our doc then we put nothing word there

In [48]:
tokenizer.fit_on_texts(docs)

In [49]:
tokenizer.word_index

{'<nothing>': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'hello': 17,
 'world': 18}

In [50]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('hello', 1),
             ('world', 1)])

In [51]:
tokenizer.document_count # no. of rows in your doc

10

In [52]:
sequences = tokenizer.texts_to_sequences(docs)

In [53]:
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [54]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences , padding = 'post') # post means after the words

In [55]:
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [56]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [57]:
(X_train, y_train),(X_test , y_test) = imdb.load_data()

In [58]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [59]:
X_train.shape

(25000,)

In [60]:
X_test.shape

(25000,)

In [61]:
len(X_train[0])

218

In [62]:
len(X_train[1])

189

In [63]:
# As we can see they are not padded each row ...
X_train = pad_sequences(X_train , padding = 'post' , maxlen = 50)
X_test = pad_sequences(X_test , padding='post' , maxlen=50) # we are limitting to 50 words because the dataset is huge

In [64]:
model = Sequential()

model.add(SimpleRNN(32 , input_shape = (50,1)  , return_sequences = False))
model.add(Dense(1 , activation = 'sigmoid'))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [65]:
model.compile(loss='binary_crossentropy' , optimizer='adam' , metrics = ['accuracy'])
model.fit(X_train , y_train , epochs = 5,validation_data = (X_test , y_test))

Epoch 1/5
518/782 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.4937 - loss: 0.7025

KeyboardInterrupt: 

### Embedding


In [66]:
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [67]:
model2 = Sequential()
model2.add(Embedding(17 , output_dim=2 , input_length = 5)) # 17 words , every word must be represented through 2 numbers (this is a hyperparameter, you tune and find out)
# input length tells how many words in each row
model2.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [70]:
model2.compile('adam','accuracy')

In [72]:
pred = model2.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step
[[[-0.02066248  0.01720277]
  [-0.02928742  0.03560516]
  [ 0.02191002  0.01103015]
  [ 0.02191002  0.01103015]
  [ 0.02191002  0.01103015]]

 [[-0.02928742  0.03560516]
  [-0.02928742  0.03560516]
  [ 0.02191002  0.01103015]
  [ 0.02191002  0.01103015]
  [ 0.02191002  0.01103015]]

 [[-0.02456615  0.03789834]
  [-0.02456615  0.03789834]
  [ 0.03213221  0.02205975]
  [ 0.02191002  0.01103015]
  [ 0.02191002  0.01103015]]

 [[ 0.02985925  0.04723929]
  [-0.04262833  0.0246619 ]
  [ 0.02985925  0.04723929]
  [-0.02928742  0.03560516]
  [ 0.02985925  0.04723929]]

 [[ 0.03906145 -0.00758814]
  [ 0.03105957  0.03507503]
  [-0.0231239  -0.00187634]
  [ 0.03153991 -0.04673232]
  [ 0.02191002  0.01103015]]

 [[-0.02726558 -0.00386634]
  [-0.02726558 -0.00386634]
  [ 0.02191002  0.01103015]
  [ 0.02191002  0.01103015]
  [ 0.02191002  0.01103015]]

 [[ 0.02492983  0.03731454]
  [ 0.02492983  0.03731454]
  [ 0.02191002  0.01103015]
  [ 0.02191002  0.0110301

### work on imdb

In [74]:
X_train.shape

(25000, 50)

In [79]:
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=2, input_length=50))
model.add(SimpleRNN(32 , return_sequences=False))
model.add(Dense(1,activation='sigmoid' ))
model.build(input_shape=(None, 50))
model.summary()

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_10 (Embedding)        │ (None, 50, 2)          │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_5 (SimpleRNN)        │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [80]:
model.compile(optimizer='adam' , loss = 'binary_crossentropy', metrics = ['acc'])
history = model.fit(X_train , y_train , epochs = 5 , validation_data=(X_test , y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - acc: 0.5221 - loss: 0.6877 - val_acc: 0.7839 - val_loss: 0.4684
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - acc: 0.8099 - loss: 0.4232 - val_acc: 0.7927 - val_loss: 0.4499
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - acc: 0.8561 - loss: 0.3447 - val_acc: 0.8002 - val_loss: 0.4434
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - acc: 0.8772 - loss: 0.3112 - val_acc: 0.7895 - val_loss: 0.4641
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - acc: 0.8725 - loss: 0.3212 - val_acc: 0.7853 - val_loss: 0.5098


> you can apply embedding using word2vec etc but generally its said to apply embedding via model learning method that is above only because here model learns and applies those embeddings based in your dataset, that is it captures your dataset's semantic meanings
